# Generated by Django 4.2.14 on 2024-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_alter_article_options_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together={('article', 'tag')},
        ),
    ]
