# Generated by Django 4.2.14 on 2024-08-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_is_main_alter_scope_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='Изображение'),
        ),
    ]
